-   id: gbp-pre-commit-hooks-pull
    name: gbp pre commit hooks pull
    entry: bash -c '(cd ~/.cache/pre-commit/gbp-pre-commit-hooks && git pull && cd -) || (echo "Cannot update gbp pre commit hooks!" && exit 1)'
    language: system
    always_run: true
-   id: gbp-no-commit-to-branch
    name: gbp no commit to branch
    entry: bash -c 'PYTHONPATH=~/.cache/pre-commit/gbp-pre-commit-hooks python3 -m gbp_pre_commit_hooks.no_commit_to_branch -b upstream'
    language: system
    pass_filenames: false
    always_run: true
-   id: gbp-ensure-copyright
    name: gbp ensure copyright
    entry: bash -c 'grep -qPi "20\d\d\s+debian" debian/copyright || (echo "Missing debian copyright!" && exit 1)'
    language: system
    always_run: true
    types: [file]
    files: ^debian/copyright$
-   id: gbp-conf-base-check
    name: gbp conf base check
    entry: bash -c 'comm -13 <(sort -u debian/gbp.conf) <(sort -u ~/.cache/pre-commit/gbp-pre-commit-hooks/assets/gbp.conf) | grep -q '[^[:space:]]'; exit $((! $?)) || (echo "File gbp.conf does not meet company standard!" && exit 1)'
    language: system
    always_run: true
    types: [file]
    files: ^debian/gbp.conf$
