-   id: gbp-pre-commit-hooks-pull
    name: gbp pre commit hooks pull
    entry: gbp_pre_commit_hooks_pull
    entry: bash -c '(cd ~/.cache/pre-commit/gbp-pre-commit-hooks && git pull && cd -) || (echo "Cannot update gbp pre commit hooks!" && exit 1)'
    language: system
    always_run: true
-   id: gbp-no-commit-to-branch
    name: gbp no commit to branch
    entry: python -m gbp_pre_commit_hooks.no_commit_to_branch
    language: system
    pass_filenames: false
    always_run: true
-   id: gbp-ensure-copyright
    name: gbp ensure copyright
    entry: bash -c 'grep -qPi "20\d\d\s+debian" debian/copyright || (echo "Missing debian copyright!" && exit 1)'
    language: system
    always_run: true
    types: [file]
    files: ^debian/copyright$
